

#ifdef BOARD_SENUP18xTH_V0010 

#define HARDWARE_NAME "SEN-UP1-8xTH V00.10"

#define OKNXHW_UP1_CONTROLLER2040
#include "OpenKNXHardware.h"

#define INFO_LED_PIN 13
#define INFO_LED_PIN_ACTIVE_ON HIGH


#define THPCHANNEL_A_SCL 29
#define THPCHANNEL_A_SDA 28
#define THPCHANNEL_B_SCL 27
#define THPCHANNEL_B_SDA 26
#define THPCHANNEL_C_SCL 25
#define THPCHANNEL_C_SDA 24
#define THPCHANNEL_D_SCL 23
#define THPCHANNEL_D_SDA 22
#define THPCHANNEL_E_SCL 21
#define THPCHANNEL_E_SDA 20
#define THPCHANNEL_F_SCL 19
#define THPCHANNEL_F_SDA 18
#define THPCHANNEL_G_SCL 17
#define THPCHANNEL_G_SDA 16
#define THPCHANNEL_H_SCL 15
#define THPCHANNEL_H_SDA 14
#endif